### ISSUE TITLE
Support for Swift 3

### ISSUE THREAD

**Issue by cristinaITdeveloper** [BlueBiteLLC/eddystone-ios#3]
Hello! Nice library, I use it in my project but I have this problem with Xcode 8 and Swift 3.

<img width="1121" alt="schermata 2016-10-22 alle 14 50 46" src="https://cloud.githubusercontent.com/assets/11472348/19619422/0c404982-9867-11e6-93fc-4dff9499ab61.png">

How can I resolve this problem?
Thank you for support!

**Comment by southfox** [comment]
Hi @cristinaITdeveloper, I did the following PR https://github.com/BlueBiteLLC/eddystone-ios/pull/4, please review and give me a buddy build if everything works.

Thanks.
Javier

**Comment by munirwanis** [comment]
I think this should be closed since there is a new release #8 with Swift 3 support.
